export const ResCardItems = [
    {
      images: ['/Best1.svg', '/Best2.svg', '/Best3.svg'],
      title: 'The snug',
      subtitle: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.',
      rating: '/4.5Star.svg',
      ratingtitle: '4.5',
      ratingsub: '654 reviews',
    },
    {
        images: ['/Best2.svg', '/Best3.svg', '/Best1.svg'],
        title: 'Bottega',
        subtitle: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.',
        rating: '/5Star.svg',
        ratingtitle: '5.0',
        ratingsub: '1654 reviews',
      },
      {
        images: ['/Best3.svg', '/Best4.svg', '/Best5.svg'],
        title: 'Little Shucker',
        subtitle: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.',
        rating: '/3Star.svg',
        ratingtitle: '3.0',
        ratingsub: '553 reviews',
      },
      {
        images: ['/Best4.svg', '/Best5.svg', '/Best6.svg'],
        title: 'Lokma',
        subtitle: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.',
        rating: '/4.5Star.svg',
        ratingtitle: '4.5',
        ratingsub: '654 reviews',
      },
      {
        images: ['/Best5.svg', '/Best6.svg', '/Best7.svg'],
        title: 'Starbelly',
        subtitle: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.',
        rating: '/4.5Star.svg',
        ratingtitle: '4.5',
        ratingsub: '654 reviews',
      },
      {
        images: ['/Best6.svg', '/Best7.svg', '/Best1.svg'],
        title: 'The melt',
        subtitle: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.',
        rating: '/4.5Star.svg',
        ratingtitle: '4.5',
        ratingsub: '654 reviews',
      },
      {
        images: ['/Best7.svg', '/Best4.svg', '/Best2.svg'],
        title: 'Arabia Nights',
        subtitle: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.',
        rating: '/4.5Star.svg',
        ratingtitle: '4.5',
        ratingsub: '654 reviews',
      },
]