export const TrendCards = [
    {
        image: ['/Timage1.svg', '/Timage2.svg', '/Timage3.svg', '/Timage4.svg'],
        title: 'Bella Italia',
        subtitle: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.',
        rating: '4.8Star.svg',
        ratingtitle: '4.8',
        ratingsub: '34 reviews',
    },
    {
        image: ['/Timage2.svg', '/Timage3.svg', '/Timage4.svg', '/Timage1.svg'],
        title: 'Little Shucker',
        subtitle: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.',
        rating: '5Star.svg',
        ratingtitle: '5.0',
        ratingsub: '253 reviews',
    },
    {
        image: ['/Timage3.svg', '/Timage4.svg', '/Timage1.svg', '/Timage2.svg'],
        title: 'Marafuku Ramen',
        subtitle: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.',
        rating: '3.5Star.svg',
        ratingtitle: '3.5',
        ratingsub: '87 reviews',
    },
    {
        image: ['/Timage4.svg', '/Timage1.svg', '/Timage2.svg', '/Timage3.svg'],
        title: 'Bottega',
        subtitle: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.',
        rating: '5Star.svg',
        ratingtitle: '5.0',
        ratingsub: '876 reviews',
    },
    {
        image: ['/Timage5.svg', '/Timage6.svg', '/Timage7.svg', '/Timage8.svg'],
        title: 'Arabia Nights',
        subtitle: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.',
        rating: '3.5Star.svg',
        ratingtitle: '3.5',
        ratingsub: '234 reviews',
    },
    {
        image: ['/Timage6.svg', '/Timage7.svg', '/Timage8.svg', '/Timage5.svg'],
        title: 'Lokma',
        subtitle: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.',
        rating: '5Star.svg',
        ratingtitle: '5.0',
        ratingsub: '253 reviews',
    },
    {
        image: ['/Timage7.svg', '/Timage8.svg', '/Timage5.svg', '/Timage6.svg'],
        title: 'The snug',
        subtitle: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.',
        rating: '4.5Star.svg',
        ratingtitle: '4.5',
        ratingsub: '654 reviews',
    },
    {
        image: ['/Timage8.svg', '/Timage5.svg', '/Timage6.svg', '/Timage7.svg'],
        title: 'Starbelly',
        subtitle: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.',
        rating: '5Star.svg',
        ratingtitle: '5.0',
        ratingsub: '876 reviews',
    },
    {
        image: ['/Timage9.svg', '/Timage10.svg', '/Timage11.svg', '/Timage12.svg'],
        title: 'Iori',
        subtitle: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.',
        rating: '3.5Star.svg',
        ratingtitle: '3.5',
        ratingsub: '334 reviews',
    },
    {
        image: ['/Timage10.svg', '/Timage11.svg', '/Timage12.svg', '/Timage9.svg'],
        title: 'Ngalley',
        subtitle: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.',
        rating: '5Star.svg',
        ratingtitle: '5.0',
        ratingsub: '253 reviews',
    },
    {
        image: ['/Timage11.svg', '/Timage12.svg', '/Timage9.svg', '/Timage10.svg'],
        title: 'diogonal',
        subtitle: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.',
        rating: '4.5Star.svg',
        ratingtitle: '4.5',
        ratingsub: '876 reviews',
    },
    {
        image: ['/Timage12.svg', '/Timage9.svg', '/Timage10.svg', '/Timage11.svg'],
        title: 'Kitoko',
        subtitle: 'The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.',
        rating: '5Star.svg',
        ratingtitle: '5.0',
        ratingsub: '876 reviews',
    },

]